# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    api_key = app_store_connect_api_key(
      key_id: "ZFT55UD772",
      issuer_id: "2709c033-4111-4219-a820-78972aa0dd7a",
      key_filepath: "AuthKey_ZFT55UD772.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    setup_circle_ci
  end
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    increment_build_number(xcodeproj: "CircleCiRNDemoApp.xcodeproj")
    build_app(workspace: "CircleCiRNDemoApp.xcworkspace", scheme: "CircleCiRNDemoApp")
    upload_to_testflight
  end
end
